@startuml
title Internet Banking System - System Context

top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person_Ext(1, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.")
System(2, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")
System(4, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")
System(6, "E-mail System", "The internal Microsoft Exchange e-mail system.")

Rel_D(1, 2, "Views account balances, and makes payments using")
Rel_D(2, 4, "Gets account information from, and makes payments using")
Rel_D(2, 6, "Sends e-mail using")
Rel_D(6, 1, "Sends e-mails to")

SHOW_LEGEND()
@enduml