@startuml
title System Landscape for Big Bank plc

top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Enterprise_Boundary(enterprise, "Big Bank plc") {
  Person(CustomerServiceStaff, "Customer Service Staff", "Customer service staff within the bank.")
  Person(BackOfficeStaff, "Back Office Staff", "Administration and support staff within the bank.")
  System(InternetBankingSystem, "Internet Banking System", "Allows customers to view information about their bank accounts, and make payments.")
  System(MainframeBankingSystem, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")
  System(EmailSystem, "E-mail System", "The internal Microsoft Exchange e-mail system.")
  System(ATM, "ATM", "Allows customers to withdraw cash.")
}

Person_Ext(PersonalBankingCustomer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts.")

Rel_D(ATM, MainframeBankingSystem, "Uses")
Rel_D(PersonalBankingCustomer, ATM, "Withdraws cash using")
Rel_D(CustomerServiceStaff, MainframeBankingSystem, "Uses")
Rel_D(PersonalBankingCustomer, CustomerServiceStaff, "Asks questions to", "Telephone")
Rel_D(BackOfficeStaff, MainframeBankingSystem, "Uses")
Rel_D(PersonalBankingCustomer, InternetBankingSystem, "Views account balances, and makes payments using")
Rel_D(InternetBankingSystem, MainframeBankingSystem, "Gets account information from, and makes payments using")
Rel_D(InternetBankingSystem, EmailSystem, "Sends e-mail using")
Rel_D(EmailSystem, PersonalBankingCustomer, "Sends e-mails to")

SHOW_LEGEND()
@enduml