@startuml
title Spring PetClinic - Deployment - Default

left to right direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

Deployment_Node(Default.AmazonWebServices, "Amazon Web Services") {
  Deployment_Node(Default.AmazonWebServices.USEast1, "US-East-1") {
    Deployment_Node(Default.AmazonWebServices.USEast1.AmazonRDS, "Amazon RDS") {
      Deployment_Node(Default.AmazonWebServices.USEast1.AmazonRDS.MySQL, "MySQL") {
        ContainerDb(Default.AmazonWebServices.USEast1.AmazonRDS.MySQL.Database_1, "Database", "Relational database schema", "Stores information regarding the veterinarians, the clients, and their pets.")
      }

    }

    Deployment_Node(Default.AmazonWebServices.USEast1.Autoscalinggroup, "Autoscaling group") {
      Deployment_Node(Default.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2, "Amazon EC2") {
        Container(Default.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2.WebApplication_1, "Web Application", "Java and Spring Boot", "Allows employees to view and manage information regarding the veterinarians, the clients, and their pets.")
      }

    }

    Deployment_Node(Default.AmazonWebServices.USEast1.ElasticLoadBalancer, "Elastic Load Balancer")
    Deployment_Node(Default.AmazonWebServices.USEast1.Route53, "Route 53")
  }

}

Rel_D(Default.AmazonWebServices.USEast1.Route53, Default.AmazonWebServices.USEast1.ElasticLoadBalancer, "Forwards requests to", "HTTPS")
Rel_D(Default.AmazonWebServices.USEast1.ElasticLoadBalancer, Default.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2.WebApplication_1, "Forwards requests to", "HTTPS")
Rel_D(Default.AmazonWebServices.USEast1.Autoscalinggroup.AmazonEC2.WebApplication_1, Default.AmazonWebServices.USEast1.AmazonRDS.MySQL.Database_1, "Reads from and writes to", "JDBC/SSL")

SHOW_LEGEND()
@enduml