@startuml
title System Landscape for Enterprise

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Enterprise_Boundary(enterprise, "Enterprise") {
  Boundary(group_0, "Group 2") {
    System(D, "D", "", $tags="Element+Software System")
  }

  System(C, "C", "", $tags="Element+Software System")
}

Boundary(group_1, "Group 1") {
  System_Ext(B, "B", "", $tags="Element+Software System")
}

System_Ext(A, "A", "", $tags="Element+Software System")

Rel_D(B, C, "", $tags="Relationship")
Rel_D(C, D, "", $tags="Relationship")
Rel_D(A, B, "", $tags="Relationship")

SHOW_LEGEND()
@enduml