@startuml
title D - F - Components

top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System(C, "C", "")

Container_Boundary("D.F_boundary", "F") {
  Boundary(group_3, "Group 4") {
    Component(D.F.H, "H", "")
  }

  Component(D.F.G, "G", "")
}

Rel_D(C, D.F.G, "")
Rel_D(C, D.F.H, "")

SHOW_LEGEND()
@enduml