@startuml
title D - Containers

top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System(3, "C", "")

System_Boundary("4_boundary", "D") {
  Boundary(group_2, "Group 3") {
    Container(6, "F", "")
  }

  Container(5, "E", "")
}

Rel_D(3, 5, "")
Rel_D(3, 6, "")

SHOW_LEGEND()
@enduml