@startuml
title D - Containers

top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System(C, "C", "")

System_Boundary("D_boundary", "D") {
  Boundary(group_2, "Group 3") {
    Container(D.F, "F", "")
  }

  Container(D.E, "E", "")
}

Rel_D(C, D.E, "")
Rel_D(C, D.F, "")

SHOW_LEGEND()
@enduml