@startuml
title System Landscape for Enterprise

top to bottom direction

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Enterprise_Boundary(enterprise, "Enterprise") {
  Boundary(group_0, "Group 2") {
    System(D, "D", "")
  }

  System(C, "C", "")
}

Boundary(group_1, "Group 1") {
  System_Ext(B, "B", "")
}

System_Ext(A, "A", "")

Rel_D(B, C, "")
Rel_D(C, D, "")
Rel_D(A, B, "")

SHOW_LEGEND()
@enduml