@startuml
title Internet Banking System - Deployment - Live

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  PackageBorderColor<<group>> #cccccc
  PackageFontColor<<group>> #cccccc
}

hide stereotype

skinparam rectangle<<81>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam node<<80>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<76>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<72>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<69>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<67>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam database<<91>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam database<<87>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam rectangle<<74>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}
skinparam rectangle<<68>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam node<<86>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<90>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam rectangle<<71>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam rectangle<<77>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam node<<70>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<79>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<85>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<89>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<73>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}
skinparam node<<75>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #888888
}

node "Customer's mobile device\n[Deployment Node: Apple iOS or Android]" <<67>> as 67 {
  rectangle "==Mobile App\n<size:10>[Container: Xamarin]</size>\n\nProvides a limited subset of the Internet banking functionality to customers via their mobile device." <<68>> as 68
}

node "Customer's computer\n[Deployment Node: Microsoft Windows or Apple macOS]" <<69>> as 69 {
  node "Web Browser\n[Deployment Node: Chrome, Firefox, Safari, or Edge]" <<70>> as 70 {
    rectangle "==Single-Page Application\n<size:10>[Container: JavaScript and Angular]</size>\n\nProvides all of the Internet banking functionality to customers via their web browser." <<71>> as 71
  }

}

node "Big Bank plc\n[Deployment Node: Big Bank plc data center]" <<72>> as 72 {
  node "bigbank-api*** (x8)\n[Deployment Node: Ubuntu 16.04 LTS]" <<79>> as 79 {
    node "Apache Tomcat\n[Deployment Node: Apache Tomcat 8.x]" <<80>> as 80 {
      rectangle "==API Application\n<size:10>[Container: Java and Spring MVC]</size>\n\nProvides Internet banking functionality via a JSON/HTTPS API." <<81>> as 81
    }

  }

  node "bigbank-db01\n[Deployment Node: Ubuntu 16.04 LTS]" <<85>> as 85 {
    node "Oracle - Primary\n[Deployment Node: Oracle 12c]" <<86>> as 86 {
      database "==Database\n<size:10>[Container: Oracle Database Schema]</size>\n\nStores user registration information, hashed authentication credentials, access logs, etc." <<87>> as 87
    }

  }

  node "bigbank-db02\n[Deployment Node: Ubuntu 16.04 LTS]" <<89>> as 89 {
    node "Oracle - Secondary\n[Deployment Node: Oracle 12c]" <<90>> as 90 {
      database "==Database\n<size:10>[Container: Oracle Database Schema]</size>\n\nStores user registration information, hashed authentication credentials, access logs, etc." <<91>> as 91
    }

  }

  node "bigbank-prod001\n[Deployment Node]" <<73>> as 73 {
    rectangle "==Mainframe Banking System\n<size:10>[Software System]</size>\n\nStores all of the core banking information about customers, accounts, transactions, etc." <<74>> as 74
  }

  node "bigbank-web*** (x4)\n[Deployment Node: Ubuntu 16.04 LTS]" <<75>> as 75 {
    node "Apache Tomcat\n[Deployment Node: Apache Tomcat 8.x]" <<76>> as 76 {
      rectangle "==Web Application\n<size:10>[Container: Java and Spring MVC]</size>\n\nDelivers the static content and the Internet banking single page application." <<77>> as 77
    }

  }

}

77 .[#707070,thickness=2].> 71 : "<color:#707070>Delivers to the customer's web browser"
68 .[#707070,thickness=2].> 81 : "<color:#707070>Makes API calls to\n<color:#707070><size:8>[JSON/HTTPS]</size>"
71 .[#707070,thickness=2].> 81 : "<color:#707070>Makes API calls to\n<color:#707070><size:8>[JSON/HTTPS]</size>"
81 .[#707070,thickness=2].> 74 : "<color:#707070>Makes API calls to\n<color:#707070><size:8>[XML/HTTPS]</size>"
81 .[#707070,thickness=2].> 87 : "<color:#707070>Reads from and writes to\n<color:#707070><size:8>[JDBC]</size>"
81 .[#707070,thickness=2].> 91 : "<color:#707070>Reads from and writes to\n<color:#707070><size:8>[JDBC]</size>"
86 .[#707070,thickness=2].> 90 : "<color:#707070>Replicates data to"
@enduml