@startuml
title Spring PetClinic - Deployment - Default

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  PackageBorderColor<<group>> #cccccc
  PackageFontColor<<group>> #cccccc
}
hide stereotype
left to right direction

skinparam node<<8>> {
  BackgroundColor #ffffff
  FontColor #d86613
  BorderColor #d86613
}
skinparam node<<14>> {
  BackgroundColor #ffffff
  FontColor #3b48cc
  BorderColor #3b48cc
}
skinparam node<<5>> {
  BackgroundColor #ffffff
  FontColor #232f3e
  BorderColor #232f3e
}
skinparam node<<7>> {
  BackgroundColor #ffffff
  FontColor #cc2264
  BorderColor #cc2264
}
skinparam database<<16>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #b2b2b2
}
skinparam rectangle<<11>> {
  BackgroundColor #ffffff
  FontColor #693cc5
  BorderColor #693cc5
  roundCorner 20
}
skinparam node<<15>> {
  BackgroundColor #ffffff
  FontColor #3b48cc
  BorderColor #3b48cc
}
skinparam rectangle<<10>> {
  BackgroundColor #ffffff
  FontColor #693cc5
  BorderColor #693cc5
  roundCorner 20
}
skinparam node<<6>> {
  BackgroundColor #ffffff
  FontColor #147eba
  BorderColor #147eba
}
skinparam rectangle<<9>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #b2b2b2
  roundCorner 20
}

node "Amazon Web Services\n[Deployment Node]" <<5>> as 5 {
  node "US-East-1\n[Deployment Node]" <<6>> as 6 {
    node "Amazon RDS\n[Deployment Node]" <<14>> as 14 {
      node "MySQL\n[Deployment Node]" <<15>> as 15 {
        database "==Database\n<size:10>[Container: Relational database schema]</size>\n\nStores information regarding the veterinarians, the clients, and their pets." <<16>> as 16
      }

    }

    node "Autoscaling group\n[Deployment Node]" <<7>> as 7 {
      node "Amazon EC2\n[Deployment Node]" <<8>> as 8 {
        rectangle "==Web Application\n<size:10>[Container: Java and Spring Boot]</size>\n\nAllows employees to view and manage information regarding the veterinarians, the clients, and their pets." <<9>> as 9
      }

    }

    rectangle "==Elastic Load Balancer\n<size:10>[Infrastructure Node]</size>" <<11>> as 11
    rectangle "==Route 53\n<size:10>[Infrastructure Node]</size>" <<10>> as 10
  }

}

10 .[#707070,thickness=2].> 11 : "<color:#707070>Forwards requests to\n<color:#707070><size:8>[HTTPS]</size>"
11 .[#707070,thickness=2].> 9 : "<color:#707070>Forwards requests to\n<color:#707070><size:8>[HTTPS]</size>"
9 .[#707070,thickness=2].> 16 : "<color:#707070>Reads from and writes to\n<color:#707070><size:8>[JDBC/SSL]</size>"
@enduml