@startuml
title D - F - Components

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  PackageBorderColor<<group>> #cccccc
  PackageFontColor<<group>> #cccccc
}

hide stereotype

skinparam rectangle<<C>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<D.F.G>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<D.F.H>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}

rectangle "==C\n<size:10>[Software System]</size>" <<C>> as C

package "F\n[Container]" <<D.F>> {
  skinparam PackageBorderColor<<D.F>> #444444
  skinparam PackageFontColor<<D.F>> #444444

  package "Group 4\n[Group]" <<group>> {
    rectangle "==H\n<size:10>[Component]</size>" <<D.F.H>> as D.F.H
  }

  rectangle "==G\n<size:10>[Component]</size>" <<D.F.G>> as D.F.G
}

C .[#707070,thickness=2].> D.F.G : "<color:#707070>"
C .[#707070,thickness=2].> D.F.H : "<color:#707070>"
@enduml